language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
  - npm install -g serverless
script:
  - npm run lint
  - npm run test
  - sls deploy --stage dev -v
  - npm run integration
deploy:
  provider: script
  script: - sls deploy --stage prod
