// tests for createUrl
// Generated by serverless-jest-plugin

const jestPlugin = require('serverless-jest-plugin');

const mod = require('./../createUrl');

const { lambdaWrapper } = jestPlugin;
const wrapped = lambdaWrapper.wrap(mod, { handler: 'run' });

describe('createUrl', () => {
  beforeAll((done) => {
    //  lambdaWrapper.init(liveFunction); // Run the deployed lambda

    done();
  });

  it('implement tests here', () => wrapped.run({}).then((response) => {
    expect(response).toBeDefined();
  }));
});
